# Generated by Django 3.0 on 2025-09-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250927_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
